events {}

http {
    limit_req_zone $binary_remote_addr zone=my_zone:10m rate=5r/s; # настраиваем ограничение запросов 1 запрос в секунду
    limit_req_status 429;

    server {
        listen 443 ssl;

        location / {
            limit_req zone=my_zone; # используем настроенное ограничение запросов
            proxy_pass http://hotels_back:8000/;
        }

        ssl_certificate /etc/letsencrypt/live/hotels-my-study-project-test.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/hotels-my-study-project-test.ru/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf; # нужно для Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # нужно для Certbot
    }
}