"""rename password col in users

Revision ID: bc12573b9dd7
Revises: f017a1aa43e1
Create Date: 2025-09-12 21:42:56.886917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc12573b9dd7"
down_revision: Union[str, Sequence[str], None] = "f017a1aa43e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=200), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
